# src/goes_natural_science_kg/schemas/sequencing.py
# AI Depto
# Copyright 2026 Gobierno de El Salvador.
# SPDX-License-Identifier: Apache-2.0
# Mission: Define auditable finite activity banks and solver certificates.
from __future__ import annotations

from datetime import date
from typing import Annotated, Any, Literal, Self

from pydantic import Field, model_validator

from goes_natural_science_kg.schemas.base import (
    Contract,
    Digest,
    Grade,
    PositiveMinutes,
    References,
    Slug,
    StableId,
    Text,
)
from goes_natural_science_kg.schemas.corpus import SourceUrl
from goes_natural_science_kg.schemas.curriculum import ContextTag
from goes_natural_science_kg.schemas.graph import EvidenceGraphSnapshot, GraphSnapshot
from goes_natural_science_kg.schemas.skills import CognitiveDomain, EdgeType


class ContextEvidence(Contract):
    claim: Text
    source_url: SourceUrl
    retrieved_at: date
    confidence: Literal["high", "medium", "low"]


class LocalContext(Contract):
    id: Slug
    label: Text
    tags: Annotated[tuple[ContextTag, ...], Field(min_length=1)]
    pisa_scope: Literal["personal", "local-national", "global"]
    evidence: Annotated[tuple[ContextEvidence, ...], Field(min_length=1)]


class LearningActivity(Contract):
    id: Slug
    micro_skill_ids: Annotated[References, Field(min_length=1)]
    kind: Literal["teach", "practice", "retrieval", "bridge", "assessment"]
    minutes: PositiveMinutes
    cognitive_domain: CognitiveDomain
    inquiry: bool = False
    theme: Slug
    task: Text
    mastery_criterion: Text
    allowed_grades: Annotated[tuple[Grade, ...], Field(min_length=1)]
    mandatory: bool = False
    # Contextualized wording is authored input, never generated by the solver.
    context_tasks: dict[Slug, Text] = Field(default_factory=dict)


class ContinuityThread(Contract):
    id: Slug
    opening_activity_id: Slug
    continuation_activity_id: Slug


class SequencingInput(Contract):
    schema_version: Literal["sequencing-input/1.0"] = "sequencing-input/1.0"
    graph: GraphSnapshot | EvidenceGraphSnapshot
    approval: Literal["approved", "provisional", "engineering-fixture"]
    reviewed_by: Text | None = None
    activities: tuple[LearningActivity, ...]
    key_micro_ids: References = ()
    contexts: tuple[LocalContext, ...] = ()
    continuity: tuple[ContinuityThread, ...] = ()

    @model_validator(mode="after")
    def integrity(self) -> Self:  # noqa: C901 - closed input references are validated together
        if self.approval == "approved" and not isinstance(self.graph, EvidenceGraphSnapshot):
            raise ValueError("approved builds require a chunk-traceable graph-snapshot/2.0")
        if self.approval == "approved" and not self.reviewed_by:
            raise ValueError("approved input requires an identified reviewer")
        micros = {m.id: m for m in self.graph.micro_skills}
        contexts = {c.id for c in self.contexts}
        acts = {a.id: a for a in self.activities}
        if len(acts) != len(self.activities) or len(contexts) != len(self.contexts):
            raise ValueError("duplicate activity or context IDs")
        if not set(self.key_micro_ids) <= set(micros):
            raise ValueError("unknown key micro-skill")
        for a in self.activities:
            if not set(a.micro_skill_ids) <= set(micros) or not set(a.context_tasks) <= contexts:
                raise ValueError("activity references unknown micro-skill or context")
            if len(set(a.allowed_grades)) != len(a.allowed_grades):
                raise ValueError("duplicate allowed grades")
            if a.kind == "teach" and a.minutes < sum(
                micros[k].estimated_minutes for k in a.micro_skill_ids
            ):
                raise ValueError("teaching activity underallocates estimated micro-skill minutes")
        for edge in self.graph.edges:
            if edge.type in (EdgeType.PREREQUISITE, EdgeType.CO_REQUISITE) and (
                edge.source not in micros or edge.target not in micros
            ):
                raise ValueError(
                    "resolve skill-level dependencies to micro-skills before scheduling"
                )
        for thread in self.continuity:
            if (
                thread.opening_activity_id not in acts
                or thread.continuation_activity_id not in acts
            ):
                raise ValueError("continuity thread references unknown activity")
        object.__setattr__(self, "activities", tuple(sorted(self.activities, key=lambda a: a.id)))
        object.__setattr__(self, "contexts", tuple(sorted(self.contexts, key=lambda c: c.id)))
        object.__setattr__(self, "continuity", tuple(sorted(self.continuity, key=lambda t: t.id)))
        return self


class ObjectiveWeights(Contract):
    domain_balance: Annotated[int, Field(ge=0)] = 2
    cognitive_balance: Annotated[int, Field(ge=0)] = 5
    inquiry: Annotated[int, Field(ge=0)] = 1
    spacing: Annotated[int, Field(ge=0)] = 3
    thematic_coherence: Annotated[int, Field(ge=0)] = 1
    context_variety: Annotated[int, Field(ge=0)] = 1


class SequencingSettings(Contract):
    schema_version: Literal["sequencing-settings/1.0"] = "sequencing-settings/1.0"
    budget_hours: Annotated[int, Field(ge=1, le=400)] = 160
    seed: Annotated[int, Field(ge=0, le=2147483647)] = 42
    periods: Annotated[int, Field(ge=2, le=12)] = 4
    tolerance_percent: Literal[0] = 0
    knowing_max_percent: Annotated[int, Field(ge=0, le=100)] = 30
    reasoning_min_percent: dict[Grade, Annotated[int, Field(ge=0, le=100)]] = Field(
        default_factory=lambda: {2: 30, 3: 30, 4: 35, 5: 40, 6: 40}
    )
    domain_target_percent: dict[Text, Annotated[int, Field(ge=0, le=100)]] = Field(
        default_factory=lambda: {
            "physical-science": 34,
            "life-science": 33,
            "earth-space-science": 33,
        }
    )
    context_max_percent: Annotated[int, Field(ge=0, le=100)] = 60
    context_single_max_percent: Annotated[int, Field(ge=1, le=100)] = 25
    context_min_variety: Annotated[int, Field(ge=1)] = 3
    retrieval_target: Annotated[int, Field(ge=0, le=6)] = 2
    spacing_minutes: PositiveMinutes = 480
    max_deterministic_time: Annotated[float, Field(gt=0)] = 5.0
    weights: ObjectiveWeights = Field(default_factory=ObjectiveWeights)

    @model_validator(mode="after")
    def targets(self) -> Self:
        if set(self.reasoning_min_percent) != set(range(2, 7)):
            raise ValueError("reasoning targets required for every grade")
        if sum(self.domain_target_percent.values()) != 100:
            raise ValueError("domain targets must sum to 100 percent")
        return self


class ScheduledUnit(Contract):
    id: StableId
    activity_id: Slug
    micro_skill_ids: References
    kind: Literal["teach", "practice", "retrieval", "bridge", "assessment"]
    grade: Grade
    period: Annotated[int, Field(ge=0)]
    start_minute: Annotated[int, Field(ge=0)]
    end_minute: PositiveMinutes
    total_minutes: PositiveMinutes
    cognitive_domain: CognitiveDomain
    inquiry: bool
    theme: Slug
    task: Text
    mastery_criterion: Text
    context_id: Slug | None
    contexts: tuple[ContextTag, ...]

    @model_validator(mode="after")
    def duration(self) -> Self:
        if self.end_minute - self.start_minute != self.total_minutes:
            raise ValueError("unit interval and duration differ")
        if bool(self.context_id) != bool(self.contexts):
            raise ValueError("abstract units have no context tags")
        return self


class SolvedGradeCurriculum(Contract):
    schema_version: Literal["solved-grade-curriculum/1.0"] = "solved-grade-curriculum/1.0"
    grade: Grade
    approval: Literal["approved", "provisional", "engineering-fixture"]
    input_sha256: Digest
    settings_sha256: Digest
    total_minutes: PositiveMinutes
    budget_minutes: PositiveMinutes
    units: tuple[ScheduledUnit, ...]

    @model_validator(mode="after")
    def arithmetic(self) -> Self:
        if (
            self.total_minutes != self.budget_minutes
            or sum(u.total_minutes for u in self.units) != self.total_minutes
        ):
            raise ValueError("exact grade budget violated")
        previous = 0
        for u in self.units:
            if u.grade != self.grade or u.start_minute != previous:
                raise ValueError("units must form an ordered, gap-free grade calendar")
            previous = u.end_minute
        return self


class SolverReport(Contract):
    schema_version: Literal["solver-report/1.0"] = "solver-report/1.0"
    status: Literal["optimal", "feasible", "infeasible", "unknown", "invalid"]
    input_sha256: Digest
    settings_sha256: Digest
    solver_version: Text
    objective_value: float | None = None
    best_bound: float | None = None
    hard_errors: tuple[Text, ...] = ()
    coverage: dict[str, bool] = Field(default_factory=dict)
    grade_metrics: dict[int, dict[str, Any]] = Field(default_factory=dict)
    objective_components: dict[str, int] = Field(default_factory=dict)
    grades: tuple[SolvedGradeCurriculum, ...] = ()


class ConstraintModel(Contract):
    model: Any = Field(exclude=True)
    selected: dict[str, Any] = Field(exclude=True)
    starts: dict[str, Any] = Field(exclude=True)
    grades: dict[str, Any] = Field(exclude=True)
    placements: dict[tuple[str, int, int], Any] = Field(exclude=True)
    contexts: dict[tuple[str, str, int], Any] = Field(exclude=True)
    components: dict[str, Any] = Field(exclude=True)


class LinkedGraph(Contract):
    context: dict[str, Any] = Field(alias="@context")
    nodes: tuple[dict[str, Any], ...] = Field(alias="@graph")
